apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper 
  namespace: blixter
  labels: { app: zookeeper }
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector: { matchLabels: { app: zookeeper } }
  template:
    metadata: { labels: { app: zookeeper } }
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          ports: [containerPort: 2181]
          env:
            - { name: ZOOKEEPER_CLIENT_PORT, value: 2181 }
            - { name: ZOOKEEPER_TICK_TIME, value: 2000 }

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: blixter
spec:
  selector: { app: zookeeper }
  ports: [{ port: 2181, name: zookeeper, targetPort: 2181 }]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka 
  namespace: blixter
  labels: { app: kafka }
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector: { matchLabels: { app: kafka } }
  template:
    metadata: { labels: { app: kafka } }
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka::latest
          ports: [containerPort: 9092]
          env:
            - { name: KAFKA_BROKER_ID, value: 1 }
            - { name: KAFKA_ZOOKEEPER_CONNECT, value: zookeeper:2181 }
            - { name: KAFKA_ADVERTISED_LISTENERS, value: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092 }
            - { name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP, value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT }
            - { name: KAFKA_INTER_BROKER_LISTENER_NAME, value: PLAINTEXT }
            - { name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR, value: 1 }

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: blixter
spec:
  selector: { app: kafka }
  ports: [{ port: 9092, name: kafka, targetPort: 9092 }]
  clusterIP: 10.43.0.207
