apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: blixter
  labels: { app: postgres }
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector: { matchLabels: { app: postgres } }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports: [containerPort: 5432]
          env:
            - { name: POSTGRES_USER, valueFrom: { secretKeyRef: { name: 'postgres', key: 'POSTGRES_USER' } } }
            - { name: POSTGRES_DB, valueFrom: { secretKeyRef: { name: 'postgres', key: 'POSTGRES_DB' } } }
            - { name: POSTGRES_PASSWORD, valueFrom: { secretKeyRef: { name: 'postgres', key: 'POSTGRES_PASSWORD' } } }
      #     volumeMounts: [{ name: data, mountPath: /var/lib/postgresql }]
      # volumes:
      #   - name: data
      #     persistentVolumeClaim: { claimName: postgres }

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: blixter
spec:
  selector: { app: postgres }
  ports: [{ port: 5432, name: postgres, targetPort: 5432 }]
  clusterIP: 10.43.0.206
