name: blixter

on: [push]

jobs:
  blixter:
    name: Blixter
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependency
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: bun-${{ hashFiles('**/bun.lockb') }}

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build
        env:
          REDIS_URL: redis://localhost:6379

      - name: Production dependency
        run: bun --production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Container registry login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker (frontend)
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./apps/frontend/Dockerfile
          tags: ghcr.io/mp281x/blixter-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: docker (jobs-handler)
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./apps/jobs-handler
          file: ./apps/jobs-handler/Dockerfile
          tags: ghcr.io/mp281x/job-handler:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
